// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9oNtoG6zCG6460eHTFR5HOJbpFOOMpgA',
    appId: '1:634260015593:web:eb4e45015e45dc5458a378',
    messagingSenderId: '634260015593',
    projectId: 'agenda-eventos-d32e8',
    authDomain: 'agenda-eventos-d32e8.firebaseapp.com',
    storageBucket: 'agenda-eventos-d32e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4yFnb0V0nz-j2-ihHmanTFGsUl2vmVXU',
    appId: '1:634260015593:android:e26f2c7c0d09f95b58a378',
    messagingSenderId: '634260015593',
    projectId: 'agenda-eventos-d32e8',
    storageBucket: 'agenda-eventos-d32e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApXeVQ0Am6PPGXB8YUbACnXVdsW4JdfB4',
    appId: '1:634260015593:ios:bd9d32046d8d03db58a378',
    messagingSenderId: '634260015593',
    projectId: 'agenda-eventos-d32e8',
    storageBucket: 'agenda-eventos-d32e8.firebasestorage.app',
    iosBundleId: 'com.example.agendaGgHf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApXeVQ0Am6PPGXB8YUbACnXVdsW4JdfB4',
    appId: '1:634260015593:ios:bd9d32046d8d03db58a378',
    messagingSenderId: '634260015593',
    projectId: 'agenda-eventos-d32e8',
    storageBucket: 'agenda-eventos-d32e8.firebasestorage.app',
    iosBundleId: 'com.example.agendaGgHf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9oNtoG6zCG6460eHTFR5HOJbpFOOMpgA',
    appId: '1:634260015593:web:00563a755129781f58a378',
    messagingSenderId: '634260015593',
    projectId: 'agenda-eventos-d32e8',
    authDomain: 'agenda-eventos-d32e8.firebaseapp.com',
    storageBucket: 'agenda-eventos-d32e8.firebasestorage.app',
  );
}
